import 'aframe'
import 'aframe-cursor-teleport-component'
import 'aframe-teleport-controls'
import 'aframe-event-set-component'
import './components/proximity'
import './components/tintable'
import './components/preloader'
